trailingComma: "es5"
tabWidth: 4
semi: false
singleQuote: true
overrides:
  - files: ["*.yaml", "*.yml"]
    options:
      tabWidth: 2
      singleQuote: false
  - files: ["*.graphql"]
    options:
      tabWidth: 2
      singleQuote: false
  - files: ["*.json"]
    options:
      tabWidth: 2
      singleQuote: false
