package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"
	"fmt"

	"github.com/jhana-app/jhana-app/ent"
	"github.com/jhana-app/jhana-app/internal/authctx"
)

// Me is the resolver for me field.
func (r *queryResolver) Me(ctx context.Context) (*ent.User, error) {
	authenticatedUser, err := authctx.GetUser(ctx)
	if err != nil {
		// r.logger.Error("failed to get user from context", zap.Error(err))
		return nil, fmt.Errorf("user is not authorized")
	}

	return authenticatedUser, nil
}
