# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  tool:
    taskfile: "./ToolTasks.yaml"
    internal: true

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o ./bin/jhana ./cmd
    deps: [tool:go]

  lint:
    desc: Lint go files
    deps: [tool:go, tool:golangci-lint]
    cmds:
      - golangci-lint run {{.CLI_ARGS}}

  mod:
    desc: Update go modules and vendor directory
    deps: [tool:go]
    cmds:
      # - echo "Update go modules and vendor directory"
      - go get ./...
      - go mod tidy
      - go mod vendor

  generate:
    desc: Generate everything
    cmds:
      - task: generate-clean
      - task: generate-dataloader
      - task: generate-ent
      - task: generate-graphql
      - task: generate-no-diff

  generate-dataloader:
    desc: Generate dataloaders
    deps: [tool:go]
    silent: true
    cmds:
      - echo "Generate dataloaders"
      - go generate ./ent/dataloaders/internal/...

  generate-ent:
    desc: Generate ent files
    deps: [tool:go]
    silent: true
    cmds:
      - echo "Generate ent files"
      - go generate ./ent

  generate-graphql:
    desc: Generate graphql files
    deps: [tool:go]
    silent: true
    cmds:
      - echo "Generate graphql files"
      - go generate ./gql

  generate-no-diff:
    desc: Add generated files to .gitattributes
    silent: true
    cmds:
      - rm -f .gitattributes
      - echo "Add generated files to .gitattributes"
      - >
        grep -r 'Code generated by ent, DO NOT EDIT' ent -l | while read f; do
        echo "$f -diff" >> .gitattributes; done
      - >
        grep -r 'Code generated by ent, DO NOT EDIT' gql -l | while read f; do
        echo "$f -diff" >> .gitattributes; done
      - >
        grep -r 'Code generated by github.com/99designs/gqlgen, DO NOT EDIT' gql -l | while read f; do
        echo "$f -diff" >> .gitattributes; done

  generate-clean:
    desc: Remove generated files
    cmds:
      - task: generate-ent-clean
      - task: generate-graphql-clean

  generate-ent-clean:
    desc: Remove generated ent files
    silent: true
    cmds:
      - echo "Remove generated ent files"
      - grep -r 'Code generated by ent, DO NOT EDIT' ent -l | xargs rm
      - find ent -type d -empty -delete
      - rm ./gql/schema/ent.graphql

  generate-graphql-clean:
    desc: Remove generated graphql files
    silent: true
    cmds:
      - echo "Remove generated graphql files"
      - grep -r 'Code generated by ent, DO NOT EDIT' gql -l | xargs rm
      - grep -r 'Code generated by github.com/99designs/gqlgen, DO NOT EDIT' gql -l | xargs rm
      - find gql -type d -empty -delete
