name: jhanas
description: The first app that helps you go from zero to hero in reaching jhana.
publish_to: "none"
version: 0.0.84+44

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_power_manager: ^1.0.0
  audio_service: ^0.18.9
  audio_video_progress_bar: ^1.0.1
  auto_size_text: ^3.0.0
  crypto: ^3.0.3
  device_info_plus: ^9.0.2
  extended_image: ^8.2.0
  firebase_analytics: ^10.4.0
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.3.0
  firebase_messaging: ^14.6.0
  flutter_cache_manager: ^3.3.0
  flutter_download_manager: ^0.5.5
  flutter_markdown: ^0.6.14
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  go_router: ^8.0.1
  gql: ^1.0.0
  graphql_flutter: ^5.1.2
  graphql: ^5.1.3
  hive: ^2.2.3
  image_picker: ^1.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  just_audio: ^0.9.33
  jwt_decoder: ^2.0.1
  logging: ^1.2.0
  mindful_minutes: ^1.1.1
  normalize: ^0.8.2+1
  optimization_battery: ^0.0.7
  package_info_plus: ^4.0.2
  path_drawing: ^1.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  pausable_timer: ^2.0.0
  provider: ^6.0.5
  rxdart: ">=0.26.0 <0.28.0"
  sentry_flutter: ^7.5.2
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  vibration: ^1.7.7
  youtube_player_flutter: ^8.1.2
  gql_error_link: ^1.0.0+1

dependency_overrides:
  audio_service:
    git:
      url: https://github.com/dreadatour/audio_service.git
      path: audio_service
      ref: d14e1f525aef92cf1cb5d414c865b4083f98b994
  flutter_download_manager:
    git:
      url: https://github.com/dreadatour/flutter_download_manager.git
      ref: e38bf450d24fac56ce75805c070bdb8579058ba7

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  graphql_codegen: ^0.13.11
  json_serializable: ^6.6.1

flutter:
  assets:
    - assets/images/
    - assets/images/ambient/
    - assets/images/background/
    - assets/images/bells/
    - assets/images/icons/
    - assets/images/mocks/
    - assets/images/onboarding/
    - assets/sounds/
    - assets/sounds/ambient/
    - assets/sounds/bells/
  uses-material-design: true
