name: build-jhana-server

# Trigger the workflow on push with tags with version pattern v*.
on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

# Build docker image for etc/docker/server as jhana-server and push to the public ghcr.io registry.
# also take version number from the tag and pass it to the docker image as a tag
jobs:
  lint:
    uses: ./.github/workflows/golangci-lint.yml
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        architecture:
          - amd64
          # - arm64 # temporarily disabled because it's so slow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/jhana-app/jhana-server
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # based on https://docs.docker.com/build/ci/github-actions/cache/#cache-mounts
      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: go-build-cache
          key: ${{ runner.os }}-${{ matrix.architecture }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v2
        with:
          cache-source: go-build-cache

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: etc/docker/server/Dockerfile
          platforms: linux/${{ matrix.architecture }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    # deploy only if the push event is a tag and the tag is v*
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "::set-output name=version_tag::${GITHUB_REF/refs\/tags\//}"

      - name: Setup jhana-dev-deployment repository ssh private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_JHANA_DEV_DEPLOYMENT_DEPLOY_KEY }}

      - name: Push version to jhana-dev-deployment
        run: |
          git config --global user.name 'fikabo'
          git config --global user.email 'github@fikabo.com'
          git clone --depth 1 git@github.com:fikabo/jhana-dev-deployment.git jhana-dev-deployment
          cd jhana-dev-deployment
          git fetch origin
          git reset --hard origin/main
          echo ${{ steps.version.outputs.version_tag }} > VERSION
          git add VERSION
          git commit -m "Update version to '${{ steps.version.outputs.version_tag }}'"
          git push

      - name: Clean up
        if: always()
        run: rm -rf "$HOME/jhana-dev-deployment"
