name: golangci-lint

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
